spring:
  datasource:
    url: jdbc:postgresql://cardsdb:5431/cardsdb
    username: example
    password: example_pw
    driver-class-name: org.postgresql.Driver
    
build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

