spring:
  datasource:
    url: jdbc:postgresql://loansdb:5432/loansdb
    username: example
    password: example_pw
    driver-class-name: org.postgresql.Driver

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934

